import { getApps, initializeApp, cert } from 'firebase-admin/app'
import { getAuth } from 'firebase-admin/auth'
import { FieldValue, getFirestore } from 'firebase-admin/firestore'
export const SUPPORT_STATUSES = ['new', 'open', 'waiting_for_support', 'waiting_on_user', 'closed']
export const MESSAGE_MAX = 2000
function init() { if (!getApps().length) { const privateKey = String(process.env.FIREBASE_PRIVATE_KEY || '').trim().replace(/^['"]|['"]$/g, '').replace(/\\n/g, '\n'); initializeApp({ credential: cert({ projectId: process.env.FIREBASE_PROJECT_ID, clientEmail: process.env.FIREBASE_CLIENT_EMAIL, privateKey }) }) }; return { auth: getAuth(), db: getFirestore() } }
export async function verifyUser(req, res) { const header = req.headers.authorization || ''; if (!header.startsWith('Bearer ')) { res.status(401).json({ error: 'Unauthorized' }); return null }; try { const services = init(); const token = await services.auth.verifyIdToken(header.slice(7)); if (!token.email_verified) { res.status(403).json({ error: 'Verified email required' }); return null }; return { ...services, token } } catch { res.status(401).json({ error: 'Unauthorized' }); return null } }
export function plainText(value, name = 'message', max = MESSAGE_MAX) { if (typeof value !== 'string') throw Object.assign(new Error(`${name} is required`), { status: 400 }); const text = value.replace(/\r\n?/g, '\n').trim(); if (!text || text.length > max) throw Object.assign(new Error(`${name} must contain 1-${max} characters`), { status: 400 }); return text }
export function exactFields(body, allowed) { if (!body || typeof body !== 'object' || Array.isArray(body)) throw Object.assign(new Error('A JSON body is required'), { status: 400 }); const unexpected = Object.keys(body).find(key => !allowed.includes(key)); if (unexpected) throw Object.assign(new Error(`Unexpected field: ${unexpected}`), { status: 400 }) }
export function safeId(value) { return typeof value === 'string' && /^[A-Za-z0-9_-]{1,128}$/.test(value) ? value : null }
export function normalizeFaqText(value) { return String(value || '').toLowerCase().normalize('NFKD').replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim() }
export function matchFaqs(query, faqs, category = '') { const normalized = normalizeFaqText(query); const words = new Set(normalized.split(' ').filter(word => word.length > 2)); return faqs.map(faq => { const question = normalizeFaqText(faq.question); const keywords = Array.isArray(faq.keywords) ? faq.keywords.map(normalizeFaqText) : []; let score = category && faq.category === category ? 4 : 0; if (normalized.length >= 5 && question.includes(normalized)) score += 8; for (const word of words) { if (question.includes(word)) score += 2; if (keywords.some(keyword => keyword === word || keyword.includes(word))) score += 3 }; return { ...faq, score } }).filter(faq => faq.score >= 5).sort((a, b) => b.score - a.score || (a.sortOrder || 0) - (b.sortOrder || 0)).slice(0, 3) }
export function toIso(value) { const date = value?.toDate?.() || (value ? new Date(value) : null); return date && !Number.isNaN(date.getTime()) ? date.toISOString() : null }
export async function userContext(db, token) { const profile = await db.collection('users').doc(token.uid).get(); const data = profile.exists ? profile.data() : {}; return { ownerUid: token.uid, ownerEmail: token.email || data.email || null, ownerName: [data.firstName, data.lastName].filter(Boolean).join(' ') || data.displayName || null, organisationId: data.role === 'breeder' ? token.uid : (data.organisationId || null), organisationName: data.role === 'breeder' ? (data.kennelName || null) : (data.organisationName || null) } }
export async function enforceRateLimit(db, key, limit, windowMs, now = Date.now()) { const ref = db.collection('supportRateLimits').doc(key); await db.runTransaction(async tx => { const snap = await tx.get(ref); const data = snap.exists ? snap.data() : null; const reset = !data || typeof data.windowStart !== 'number' || now - data.windowStart >= windowMs; const count = reset ? 0 : Number(data.count || 0); if (count >= limit) throw Object.assign(new Error('Too many requests. Try again later.'), { status: 429 }); tx.set(ref, { windowStart: reset ? now : data.windowStart, count: count + 1, expiresAt: new Date(now + windowMs * 2) }) }) }
export function serverTimestamp() { return FieldValue.serverTimestamp() }
export async function confirmPersistedSupportMessage(db, conversationRef, messageRef, expectedStatus) { const [conversationSnap, messageSnap] = await Promise.all([conversationRef.get(), messageRef.get()]); const conversation = conversationSnap.exists ? conversationSnap.data() : null; const message = messageSnap.exists ? messageSnap.data() : null; if (!conversation || !message || message.conversationId !== conversationRef.id || conversation.status !== expectedStatus || !conversation.updatedAt) throw Object.assign(new Error('Support message persistence could not be confirmed'), { status: 500 }); return { conversationId: conversationRef.id, messageId: messageRef.id, status: conversation.status, updatedAt: toIso(conversation.updatedAt) } }
export function sendError(res, error, fallback = 'Support request failed') { const status = Number.isInteger(error?.status) ? error.status : 500; if (status === 500) console.error('Support operation failed'); return res.status(status).json({ error: status === 500 ? fallback : error.message }) }
