import { FormEvent, useEffect, useRef, useState } from 'react'
import { useAuth } from '../hooks/useAuth'
import './supportChat.css'
type Conversation={id:string;subject:string;status:string;userUnreadCount?:number};type Suggestion={id:string;question:string;answer:string;category:string};type Message={id:string;text:string;senderType:'user'|'admin';createdAt?:string}
export default function SupportChatWidget(){const{user}=useAuth();const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[query,setQuery]=useState('');const[category,setCategory]=useState('');const[categories,setCategories]=useState<string[]>([]);const[suggestions,setSuggestions]=useState<Suggestion[]>([]);const[conversations,setConversations]=useState<Conversation[]>([]);const[active,setActive]=useState('');const[messages,setMessages]=useState<Message[]>([]);const[message,setMessage]=useState('');const[handoff,setHandoff]=useState(false);const panel=useRef<HTMLDivElement>(null);const lock=useRef(false)
async function call(path:string,init?:RequestInit){if(!user)throw new Error('Sign in required');const token=await user.getIdToken();const r=await fetch(path,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(init?.headers||{})}});const j=await r.json();if(!r.ok)throw new Error(j.error||'Support request failed');return j}
async function load(){try{const j=await call('/api/support');setConversations(j.conversations||[]);setCategories(j.categories||[])}catch{setError('Support could not be loaded.')}}
async function loadConversation(id:string){setActive(id);try{const j=await call(`/api/support/conversations/${encodeURIComponent(id)}`);setMessages(j.messages||[]);await load()}catch{setError('Conversation could not be loaded.')}}
useEffect(()=>{if(open){load();setTimeout(()=>panel.current?.focus(),0)}},[open]);useEffect(()=>{if(!open)return;const timer=setInterval(load,30000);return()=>clearInterval(timer)},[open]);useEffect(()=>{function key(e:KeyboardEvent){if(e.key==='Escape')setOpen(false)}document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[])
async function suggest(e:FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const j=await call('/api/support',{method:'POST',body:JSON.stringify({action:'suggest',query,category})});setSuggestions(j.suggestions||[]);setHandoff((j.suggestions||[]).length===0)}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{lock.current=false;setBusy(false)}}
async function submitHandoff(e:FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);try{const j=await call('/api/support',{method:'POST',body:JSON.stringify({action:'handoff',subject:query.slice(0,120),message})});setMessage('');setHandoff(false);await load();await loadConversation(j.conversationId)}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{lock.current=false;setBusy(false)}}
async function reply(e:FormEvent){e.preventDefault();if(lock.current||!active)return;lock.current=true;setBusy(true);try{await call(`/api/support/conversations/${encodeURIComponent(active)}`,{method:'POST',body:JSON.stringify({message})});setMessage('');await loadConversation(active)}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{lock.current=false;setBusy(false)}}
const unread=conversations.reduce((n,c)=>n+Number(c.userUnreadCount||0),0)
return <div className="support-chat-root"><button className="support-chat-launcher" type="button" aria-expanded={open} aria-controls="support-chat-panel" onClick={()=>setOpen(v=>!v)}>Support{unread>0&&<span aria-label={`${unread} unread replies`}>{unread}</span>}</button>{open&&<div id="support-chat-panel" className="support-chat-panel" role="dialog" aria-modal="false" aria-label="iDogs Support" tabIndex={-1} ref={panel}><header><div><strong>iDogs Support</strong><small>We usually reply within 1 business day.</small></div><button type="button" aria-label="Close support" onClick={()=>setOpen(false)}>×</button></header><p className="support-privacy">Do not share passwords, card details or sensitive medical information.</p>{error&&<p role="alert" className="support-error">{error}</p>}{active?<><button type="button" className="support-back" onClick={()=>{setActive('');setMessages([])}}>← Conversations</button><div className="support-messages" aria-live="polite">{messages.map(m=><p key={m.id} className={`support-message ${m.senderType}`}>{m.text}</p>)}</div><form onSubmit={reply}><label htmlFor="support-reply">Reply</label><textarea id="support-reply" maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)} required/><button disabled={busy} type="submit">Send</button></form></>:<>{conversations.length>0&&<section><h3>Your conversations</h3>{conversations.map(c=><button type="button" className="support-conversation" key={c.id} onClick={()=>loadConversation(c.id)}>{c.subject}<small>{c.status.replaceAll('_',' ')}</small></button>)}</section>}<form onSubmit={suggest}><label htmlFor="support-category">FAQ category</label><select id="support-category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><label htmlFor="support-question">How can we help?</label><textarea id="support-question" maxLength={500} value={query} onChange={e=>setQuery(e.target.value)} required/><button disabled={busy} type="submit">Find answers</button></form>{suggestions.map(s=><article className="support-faq" key={s.id}><strong>{s.question}</strong><p>{s.answer}</p><div><button type="button" onClick={()=>call('/api/support',{method:'POST',body:JSON.stringify({action:'feedback',faqId:s.id,helpful:true})}).then(()=>setSuggestions([]))}>This answered my question</button><button type="button" onClick={()=>setHandoff(true)}>Talk to support</button></div></article>)}{(handoff||suggestions.length===0&&query)&&<form onSubmit={submitHandoff}><h3>Talk to support</h3><label htmlFor="support-message">Message</label><textarea id="support-message" maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)} required/><button disabled={busy} type="submit">Start conversation</button></form>}</>}</div>}</div>}
